Hi all!

I am starting getting this message when using PyPlot in Jupyter lab, tried Pkg.resolve() but it didn't help, does anyone knows how to fix this?

many thanks!!

┌ Info: Precompiling PyPlot [d330b81b-6aea-500a-939a-2ce795aea3ee]
└ @ Base loading.jl:1278
┌ Warning: Package FixedPointNumbers does not have Statistics in its dependencies:
│ - If you have FixedPointNumbers checked out for development and have
│   added Statistics as a dependency but haven't updated your primary
│   environment's manifest file, try `Pkg.resolve()`.
│ - Otherwise you may need to report an issue with FixedPointNumbers
└ Loading Statistics into FixedPointNumbers from project dependency, future warnings for FixedPointNumbers are suppressed.
